apiVersion: v1
kind: Service
metadata:
  name: jerseyservice		  # access from other pod pointing to jerseyservice:8080
spec:
  type: NodePort
  selector:
    app: jerseyspring		  # deployment
  ports:
    - targetPort: 8080 	  # port that container is listening on
      port: 8080		      # port number exposed internally in cluster
      nodePort: 30001		  # access service via this external port number
