apiVersion: v1
kind: Service
metadata:
  name: versionsartifact-service
spec:
  type: NodePort
  selector:
    app: versionsartifact
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30001
